name: r2ai-legal-assistant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - pip:
      - datasets>=2.18.0
      - rank-bm25>=0.2.2
      - sentence-transformers>=2.6.0
      - FlagEmbedding>=1.2.10
      - tqdm>=4.66.0
      - pyyaml>=6.0.1
      - jupyter>=1.0.0
